name: Deploy to Firebase

on:
  push:
    branches:
      - main # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Use the version matching your functions

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: |
          cd functions
          pip install -r requirements.txt

      - name: Deploy to Firebase
        run: firebase deploy --only functions,firestore --token "${{ secrets.FIREBASE_TOKEN }}"